"""empty message

Revision ID: 245d42a7e3e8
Revises: d21026e97b08
Create Date: 2024-07-14 20:13:50.166639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d42a7e3e8'
down_revision = 'd21026e97b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
