"""empty message

Revision ID: 43252bf8a9df
Revises: 245d42a7e3e8
Create Date: 2024-07-14 20:17:31.139673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43252bf8a9df'
down_revision = '245d42a7e3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)

    # ### end Alembic commands ###
