"""empty message

Revision ID: 58a2c105b773
Revises: fffede2123fb
Create Date: 2024-07-15 15:41:47.806740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a2c105b773'
down_revision = 'fffede2123fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_id', sa.INTEGER(), nullable=True),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
