"""empty message

Revision ID: 699355785cb3
Revises: 54ca87b567cd
Create Date: 2024-07-30 12:44:15.004792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699355785cb3'
down_revision = '54ca87b567cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_likes')
    # ### end Alembic commands ###
